In [1]:
# Install Numpy
! pip install numpy

You should consider upgrading via the 'c:\users\milan amrut joshi\anaconda3\python.exe -m pip install --upgrade pip' command.


In [2]:
import numpy as np

In [3]:
l = [1,2,3,4]
type(l)

list

In [4]:
a = np.array(l)
print(a)

[1 2 3 4]


In [5]:
type(a)

numpy.ndarray

In [6]:
a.shape

(4,)

In [12]:
# Create 1D numpy array of zeros
# Use 'zeros()' function to create an array of zeros 
#np.zeros(shape=4)
np.zeros(4)

array([0., 0., 0., 0.])

In [20]:
# Create 1D numpy array of zeros
# Use 'ones()' function to create an array of zeros 
np.ones(4)

array([1., 1., 1., 1.])

In [22]:
# Creating numpy array of random numbers between 0 to 1
# random()
#np.random.random(size=10)
np.random.random(4)  # These numbers are generated from unifrom distribution

array([0.57551955, 0.72931388, 0.28955156, 0.53960701])

In [27]:
# Generate 5 random numbers from normal distribution of mean 0 and variance 1
np.random.randn(4)

array([ 0.18806493, -1.34082508, -0.43662859, -0.1945029 ])

In [ ]:
# Create a random integer from [low , high]....[5,20]

In [31]:
np.random.randint(5,20)  # excludes 20

19

In [34]:
np.random.randint(5,50,3)  # return 3 integers rom 5 to 49

array([45, 44, 32])

In [36]:
# Creating numpy array with arange()
num = np.arange(start=10,stop=20,step=2)  # exclude 20
print(num)

[10 12 14 16 18]


In [38]:
num = np.arange(20,40,3)
print(num)

[20 23 26 29 32 35 38]


In [ ]:
# Attributes of array
# a is numpy array then 
#size -----> a.size
#itemsize---->a.itemsize
#shape----> a.shape
# ndim----> a.ndim
# dtype--->a.dtype


In [39]:
a = np.array([1,2,3,4,5,7,8,45])

In [42]:
print('No of elements in a:',a.size)

No of elements in a: 8


In [43]:
print('Itemsize(in bytes):',a.itemsize)

Itemsize(in bytes): 4


In [44]:
print('shape :',a.shape)

shape : (8,)


In [46]:
arr= np.array([1,2,3])  # 2D array
print('Shape of arr:',arr.shape)

Shape of arr: (3,)


In [48]:
arr = np.array([(1,2,3),(4,5,6)])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
print('Shape of arr:',arr.shape)  # shape means size of matrix 2 by 3 

Shape of arr: (2, 3)


In [52]:
print('Dimension of arr:',arr.ndim)   # Row is one dimension and column is another diemsion

Dimension of arr: 2


In [ ]:
# 1D array is a vector [ 1,2,3]  Dimension = 1
# 2D array is matrix ( n by m )   Dimension = 2
# 3D array  ( 3rd order tensor) 

In [56]:
a = np.array([2,4,6,4.1])
print('type of :',a.dtype)


type of : float64


In [58]:
original_array = np.array([(4,9),(7,2),(5,6)])
print('original_array:',original_array)

original_array: [[4 9]
 [7 2]
 [5 6]]


In [59]:
original_array.shape

(3, 2)

In [60]:
# Want to reshape original_array in 2 by 3
reshaped_array=original_array.reshape(2,3)
print('reshaped_array:',reshaped_array)

reshaped_array: [[4 9 7]
 [2 5 6]]


In [63]:
a = np.array([1,2,3,4])
a.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [67]:
a = np.array([2,4,6,8,9,10])
a.reshape(3,2)  # arrange a in 2 rows and 3 coloumns

array([[ 2,  4],
       [ 6,  8],
       [ 9, 10]])

In [68]:
a = np.array([ 1,2,3,4,5,6,7,6,5,4,3,2])
a.reshape(2,6)
#a.shape(3,4)


array([[1, 2, 3, 4, 5, 6],
       [7, 6, 5, 4, 3, 2]])

In [69]:
age = np.array([23,45,18,26,34,65])

In [72]:
# Indexing Slicing an array subsetting an array

print(age[0])
print(age[2])
print(age[-1])

23
18
65


In [73]:
weight = np.array([(51,45,68),(62,74,55)])
weight.shape

(2, 3)

In [74]:
weight.ndim

2

In [76]:
weight[0]

array([51, 45, 68])

In [77]:
weight[0][0]

51

In [81]:
weight[0,:]  # Print first row and all columns 

array([51, 45, 68])

In [79]:
weight[1,:]  #Print second and all coulmns

array([62, 74, 55])

In [84]:
weight[0,:2]

array([51, 45])

In [88]:
#weight[row,clmx:clmy]
print(weight[1,1:])
print(weight[1,:2])
print(weight[1,0:1])

[74 55]
[62 74]
[62]


In [89]:
a = np.array([23,45,18,26,34,65])
print(a[2:4])

[18 26]


In [91]:
print(a[1::3])  # a[start:end:steps(gap)]

[45 34]


In [92]:
print(a[:4])

[23 45 18 26]


In [93]:
# slicing 2D array
weight = np.array([(51,45,68),(62,74,55)])

In [94]:
print(weight[1,0:2])          # All elemnets from second row and frist two columns
print(weight[1,:2])  

[62 74]
[62 74]


In [95]:
print(weight[:,1:])            # elements from 2nd and 3rd oluimn only

[[45 68]
 [74 55]]


In [97]:
print(weight[:,1:-1])

[[45]
 [74]]


In [98]:
age = np.array([13,45,22,6,14,25])
age>13

array([False,  True,  True, False,  True,  True])

In [99]:
age[age>13]

array([45, 22, 14, 25])

In [100]:
a = np.array([1,2,3])
b = np.array([2,3,4])
a+b
# ? a-b

array([3, 5, 7])

In [101]:
a*b

array([ 2,  6, 12])

In [102]:
a/b

array([0.5       , 0.66666667, 0.75      ])

In [103]:
2*a

array([2, 4, 6])

In [104]:
3*a+2*b

array([ 7, 12, 17])

In [106]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [107]:
m1= np.array([[1,2,3],[4,-2,3],[0,5,1]])

In [108]:
m1.shape

(3, 3)

In [109]:
m1.ndim

2

In [110]:
m2= np.array([[4,0,1],[2,3,0],[1,4,-3]]) # elementwise multiplication

In [111]:
m1*m2

array([[ 4,  0,  3],
       [ 8, -6,  0],
       [ 0, 20, -3]])

In [114]:
print('Give me array')
val = input()

Give me array
[1,2,3]


In [115]:
val

'[1,2,3]'

In [4]:
m1= np.array([[1,2,3],[4,-2,3],[0,5,1]])
m2= np.array([[4,0,1],[2,3,0],[1,4,-3]])
multi = m1.dot(m2)
#multi2.dot(m1)  
print('matrix multiplication:',multi)

matrix multiplication: [[11 18 -8]
 [15  6 -5]
 [11 19 -3]]


In [ ]:
# Arithemetic Functions on the array
#sum()
#min()
# power()

In [6]:
arr= np.array([14,74,84,26,56])
print('sum of all the elements = ',sum(arr))

sum of all the elements =  254


In [9]:
print( 'The minimum element is = ', min(arr))
print( 'The Maximum element is = ', max(arr))

The minimum element is =  14
The Maximum element is =  84


In [13]:
num = np.array([1,2,3,4])
print('squared_array =', np.power(num,4))

squared_array = [  1  16  81 256]


# Conactenation of array

In [14]:
x = np.array([1,4,5,7])
y = np.array([6,9,3])
z= np.array([2,7,5,9])
# cancatenate x,y and z array
np.concatenate([x,y,z])

array([1, 4, 5, 7, 6, 9, 3, 2, 7, 5, 9])

In [17]:
# concatenate 2D array
arr1= np.array([[1,3],[5,7]])
arr2= np.array([[2,4],[6,8]])

In [22]:
print('cnct_array_rows =',np.concatenate([arr1,arr2],axis=0))

cnct_array_rows = [[1 3]
 [5 7]
 [2 4]
 [6 8]]


In [21]:
print('cnct_array_clms =',np.concatenate([arr1,arr2],axis=1))  # row -->axis=0 column--->axis=1

cnct_array_clms = [[1 3 2 4]
 [5 7 6 8]]


# Stacking

In [ ]:
#stack()

In [23]:
arr1= np.array([[1,3],[5,7]])
arr2= np.array([[2,4],[6,8]])
print('stacked_array =',np.stack([arr1,arr2]))

stacked_array = [[[1 3]
  [5 7]]

 [[2 4]
  [6 8]]]


In [24]:
print('stacked_array =',np.stack([arr1,arr2],axis=1))

stacked_array = [[[1 3]
  [2 4]]

 [[5 7]
  [6 8]]]


In [25]:
# horizontal stack 
# hstack()
arr1= np.array([[1,3],[5,7]])
arr2= np.array([[2,4],[6,8]])
np.hstack([arr1,arr2])

array([[1, 3, 2, 4],
       [5, 7, 6, 8]])

In [26]:
np.vstack([arr1,arr2])

array([[1, 3],
       [5, 7],
       [2, 4],
       [6, 8]])

In [ ]:
#dstack  depthwise stack 

In [28]:
arr1= np.array([[1,3],[5,7]])
arr2= np.array([[2,4],[6,8]])
np.dstack([arr1,arr2])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [30]:
# column_stack()
x = np.array([1,2,3])
y= np.array([5,6,7])

z=np.column_stack([x,y])

In [32]:
z

array([[1, 5],
       [2, 6],
       [3, 7]])

In [33]:
arr1= np.array([[1,3],[5,7]])
arr2= np.array([[2,4],[6,8]])
np.column_stack([arr1,arr2])

array([[1, 3, 2, 4],
       [5, 7, 6, 8]])

In [ ]:
# block :- is used to assemble array from a nested list of blocks 

In [34]:
m1 = np.zeros((2,2))
m2 = np.ones((2,2))
m3 = np.ones((2,2))
m4 = np.zeros((2,2))

In [40]:
np.block([[m1,m3],[m2,m4]])

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.]])

In [44]:
# spliting
#split() # to split array into multiple subarray
arr = np.arange(9)
np.split(arr,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [45]:
arr = np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
np.split(arr,[1,3])  # An excercise for next lecture why out is below?

[array([0]), array([1, 2]), array([3, 4, 5, 6, 7, 8])]

In [ ]:
# array_split()
# hsplit()
# vsplit()
# dsplit()
# Look at all these function on google and see the outputs

# Iterating Arrays

In [52]:
age = np.array([12,23,45,67,89])

for i in age:
    print(np.sqrt(i))

3.4641016151377544
4.795831523312719
6.708203932499369
8.18535277187245
9.433981132056603


In [55]:
# add 5 to each element 
arr = np.array([[1,3,5,7],[2,4,6,8]])
for i in arr:
    print(i+5)

[ 6  8 10 12]
[ 7  9 11 13]


In [56]:
v = arr+6
print(v)

[[ 7  9 11 13]
 [ 8 10 12 14]]


In [57]:
#print ouput vertically 1,3,5,7,2,4,6,8
arr = np.array([[1,3,5,7],[2,4,6,8]])
for ele in arr:
    for j in ele:
         print(j)

1
3
5
7
2
4
6
8


In [ ]:
# iterating arrays with nditer()